#quarkus:
#  native:
#    container-build: true
#    compression:
#      level: 6

planner:
  weights:
    week:
      SUNDAY: 24
      MONDAY: 11
      TUESDAY: 11
      WEDNESDAY: 11
      THURSDAY: 11
      FRIDAY: 11
      SATURDAY: 24
    holiday: 24
  people:
    -
      name: A
      hours: 77
      unavailable: 1,5,13
    -
      name: H
      hours: 77
      unavailable: 1, 5, 13
    -
      name: M
      hours: 107
      unavailable: 1,15,3
    -
      name: P
      hours: 77
      unavailable: 17
    -
      name: T
      hours: 107
      unavailable: []
      preferred: 1,3,5,7,9
  holidays:
    - --01-01    # Confraternização Universal
    - 2023-02-20 # Carnaval
    - 2023-02-21 # Carnaval
    - 2023-04-07 # Paixão de Cristo
    - --04-21    # Tiradentes
    - --05-01    # Dia do Trabalho
    - 2023-06-08 # Corpus Christi
    - --09-07    # Independência do Brasil
    - --10-12    # Nossa Sr.a Aparecida - Padroeira do Brasil
    - --11-02    # Finados
    - --11-15    # Proclamação da República
    - --12-25    # Natal
    - --12-31    # Reveillon

