quarkus:
  banner:
    enabled: false
  log:
    category:
      "io.quarkus":
        level: WARN
      "org.optaplanner":
        level: WARN
    console:
      format: "[%rms] %p - %m %n"
planner:
  files:
    directory: "C:\\planner"
    prefix: "file-"
    suffix: "scheduled"



